# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeuMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sex', models.CharField(max_length=250)),
                ('birth', models.CharField(max_length=250)),
                ('home', models.CharField(max_length=250)),
                ('first_college', models.CharField(max_length=250)),
                ('major', models.CharField(max_length=250)),
                ('tutor', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('grade', models.CharField(max_length=250)),
            ],
        ),
    ]
