# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NS', '0003_userdetail_hobbie'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='head_pic',
            field=models.FileField(default='url("../imgs/head-boy.png")', upload_to=b''),
            preserve_default=False,
        ),
    ]
