# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NS', '0004_userdetail_head_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='head_pic',
            field=models.FileField(default='head-girl.png', upload_to=b''),
        ),
    ]
