# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NS', '0011_seumaster_second_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seumaster',
            name='second_college',
            field=models.CharField(default='seu', max_length=250, null=True),
        ),
    ]
