# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NS', '0012_auto_20161005_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='hobbie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='xingzuo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
