# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NS', '0013_auto_20161102_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', '\u7537\u751f'), ('F', '\u5973\u751f')], max_length=10, null=True),
        ),
    ]
