# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NS', '0014_auto_20161103_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='xingzuo',
            field=models.CharField(blank=True, choices=[('Vir', '\u5904\u5973\u5ea7'), ('Agr', '\u5b9d\u74f6\u5ea7'), ('Ari', '\u767d\u7f8a\u5ea7'), ('Cnc', '\u5de8\u87f9\u5ea7'), ('Cap', '\u6469\u7faf\u5ea7'), ('Gem', '\u53cc\u5b50\u5ea7'), ('Leo', '\u72ee\u5b50\u5ea7'), ('Lib', 'u\u5929\u79e4\u5ea7'), ('Psc', 'u\u53cc\u9c7c\u5ea7'), ('Sco', '\u5929\u874e\u5ea7'), ('Tau', 'u\u91d1\u725b\u5ea7'), ('Sgr', 'u\u5c04\u624b\u5ea7')], max_length=200, null=True),
        ),
    ]
