# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NS', '0016_auto_20161115_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='grade',
            field=models.CharField(choices=[('D1', '\u5927\u4e00'), ('D2', '\u5927\u4e8c'), ('D3', '\u5927\u4e09'), ('D4', '\u5927\u56db'), ('Y1', '\u7814\u4e00'), ('Y2', '\u7814\u4e8c'), ('Y3', '\u7814\u4e09'), ('B1', '\u535a\u4e00'), ('B2', '\u535a\u4e8c'), ('B3', '\u535a\u4e09')], max_length=250, null=True),
        ),
    ]
