# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NS', '0018_weixinaccountlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
