# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NS', '0019_auto_20161202_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(blank=True, default='invalid', max_length=20, null=True),
        ),
    ]
