# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NS', '0002_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='hobbie',
            field=models.CharField(default='defalut', max_length=200),
            preserve_default=False,
        ),
    ]
