# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NS', '0007_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='likeID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
