# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NS', '0009_auto_20160917_0905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set([('user', 'likeID')]),
        ),
    ]
