# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NS', '0010_auto_20161001_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='seumaster',
            name='second_college',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
